name: Python CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/Quantum\ Computing\ Simulator/src" >> $GITHUB_ENV
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f ./Quantum\ Computing\ Simulator/requirements.txt ]; then pip install -r ./Quantum\ Computing\ Simulator/requirements.txt; fi
    - name: Run tests
      run: |
        PYTHONPATH=./Quantum\ Computing\ Simulator/src pytest ./Quantum\ Computing\ Simulator/tests/
  
